language: c
os: osx
osx_image: xcode10.1
compiler: clang
env:
- COLUMNS=78
before_install:
- sudo mkdir -p /opt/macports
- sudo chown $USER:staff /opt/macports
- ./prepare-travis.sh
script:
- ./buildpspp.sh
