# Build the pspp MacOS install bundle

name: psppbundle

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '13 4 * * *'

jobs:
  # The build job will install the prebuild macports build environment and build the bundle
  build:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-12]
        pspp_build_opts: [brew, brew-nightly]
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: fredowski/gtk-mac-bundler
          ref: homebrew
          path: gtk-mac-bundler

      - name: Install build environment
        run: |
          cd gtk-mac-bundler
          make bindir=/usr/local/bin install
          brew install makeicns
          brew tap fredowski/pspp

      - name: Build pspp 
        env:
          PSPP_BUILD_OPTS: --${{ matrix.pspp_build_opts }}
        run: |
          ./buildpspp.sh $PSPP_BUILD_OPTS

      - name: Archive the pspp stable bundle
        if: ${{ matrix.pspp_build_opts == 'brew'}}
        uses: actions/upload-artifact@v4
        with:
          name: pspp MacOS stable dmg ${{ matrix.os }}
          path: "pspp-[0-9].[0-9].[0-9]-[0-9].dmg"

      - name: Archive the pspp nightly bundle
        if:  ${{ matrix.pspp_build_opts == 'brew-nightly'}}
        uses: actions/upload-artifact@v4
        with:
          name: pspp MacOS nightly dmg ${{ matrix.os }}
          path: "pspp-[0-9].[0-9].[0-9]-*.dmg"
